[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/','@openzeppeline/=lib/openzeppelin-contracts/']

[invariant] 
runs = 128
depth = 128
fail_on_revert = false